name: CI


on:
  push:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest     # windows-latest   # mac-latest
    
    steps:
      
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.




